# Generated by Django 3.1 on 2020-08-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_details',
            name='Company_ID',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='job_details',
            name='Company_Name',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='job_details',
            name='HR_Name',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='job_details',
            name='Job_Catagory',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='job_details',
            name='Job_Description',
            field=models.CharField(default='none', max_length=3000),
        ),
        migrations.AlterField(
            model_name='job_details',
            name='Job_ID',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='job_details',
            name='Job_Location',
            field=models.CharField(default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='job_details',
            name='Job_Sub_Catagory',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='job_details',
            name='Job_Title',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
