# Generated by Django 3.1 on 2020-08-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_auto_20200828_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_details',
            name='CTC',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='job_details',
            name='Company_ID',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job_details',
            name='Company_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job_details',
            name='End_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='job_details',
            name='HR_Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job_details',
            name='Job_Catagory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job_details',
            name='Job_Cate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='job_details',
            name='Job_Description',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='job_details',
            name='Job_Location',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='job_details',
            name='Job_Sub_Catagory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job_details',
            name='Job_Sub_Cate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='job_details',
            name='Job_Title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job_details',
            name='Lkup_data01',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='job_details',
            name='Max_Exp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='job_details',
            name='Min_Exp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='job_details',
            name='No_of_openings',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='job_details',
            name='Start_date',
            field=models.DateField(null=True),
        ),
    ]
